using Unity.MLAgents;
using Unity.MLAgents.Policies;
using UnityEngine;

namespace MBaske.Sensors.Audio.Util
{
    /// <summary>
    /// Enables all agents containing an <see cref="AudioSensorComponentProxy"/> during training.
    /// Sensors are updated in the order that agents were enabled. Since sensor proxies return cached
    /// observations generated by <see cref="AudioSensor"/>, we need to make sure the proxies are 
    /// enabled last.
    /// </summary>
    public class ProxyEnabler : MonoBehaviour
    {
        private void Start()
        {
            // Assuming there's one AudioSensorComponent in the scene.
            var comp = FindObjectOfType<AudioSensorComponent>();
            bool isTraining = comp.GetComponent<BehaviorParameters>().BehaviorType
                == BehaviorType.Default && Academy.Instance.IsCommunicatorOn;

            if (isTraining)
            {
                foreach (var proxy in FindObjectsOfType<AudioSensorComponentProxy>(true))
                {
                    proxy.GetComponent<Agent>().gameObject.SetActive(true);
                }
            }
        }
    }
}