behaviors:
  SpeechRecognizer:
    trainer_type: ppo
    hyperparameters:
      batch_size: 32
      buffer_size: 320
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 512
      num_layers: 1
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.8
        strength: 1.0
    time_horizon: 10
    max_steps: 30000
    summary_freq: 1000
    keep_checkpoints: 5
    checkpoint_interval: 5000
    threaded: true

  CatLocalizer:
    trainer_type: ppo
    hyperparameters:
      batch_size: 1024
      buffer_size: 10240
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 512
      num_layers: 1
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    time_horizon: 20
    max_steps: 200000
    summary_freq: 1000
    keep_checkpoints: 10
    checkpoint_interval: 10000
    threaded: true



